services:
  renovate:
    image: renovate/renovate
    command:
      - "renovate"
      - "--platform=local"
    environment:
      LOG_LEVEL: debug
    working_dir: /renovate
    volumes:
      - ${PWD}:/renovate
